### ISSUE TITLE
Exception when running `buck build`

### ISSUE THREAD

**Issue by JakeSc** [airbnb/BuckSample#1]
```
$ buck build src/ImportObjC
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🏖  Watchman reported no changes
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.0s
[2017-08-20 13:00:48.450][error][command:null][tid:313][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.StackOverflowError
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at com.google.common.collect.ImmutableSortedSet.construct(ImmutableSortedSet.java:369)
	at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:298)
	at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:321)
	at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:235)
	at com.facebook.buck.rules.TargetNodeFactory.create(TargetNodeFactory.java:124)
	at com.facebook.buck.rules.TargetNodeFactory.copyNodeWithFlavors(TargetNodeFactory.java:188)
	at com.facebook.buck.rules.TargetNode.copyWithFlavors(TargetNode.java:202)
	at com.facebook.buck.rules.TargetGraph.getInternal(TargetGraph.java:68)
	at com.facebook.buck.rules.TargetGraph.get(TargetGraph.java:78)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:132)
	at com.facebook.buck.rules.BuildRuleResolver.requireAllRules(BuildRuleResolver.java:158)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:39)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:133)

```

The stack trace is hundreds of lines long, and consists of the last three lines repeated.

**Comment by JakeSc** [comment]
I don't see this anymore after upgrading Buck from 2017.05.09.01 to 2017.05.31.01. However, I do see a compile error:
```
#import <ImportObjC/A.h>
        ^
<unknown>:0: error: failed to import bridging header 'src/ImportObjC/bridging-header.h'
```

I'll dig in and perhaps file another issue. Closing this one.

**Comment by zayhero** [comment]
@JakeSc 
The `requireRule` dead loop is caused by a bug in watchman, you can turn it off or specify `NO_BUCKD=True` in your `buck build` command to get around it.

For the import issue is caused, as what we put on the this repo [README](https://github.com/airbnb/BuckSample/blob/master/README.md), the mixed languages build does NOT work with buck master repo.
It only work with our fork https://github.com/airbnb/buck/tree/airbnb_ios_current.
